AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for chat-docker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  ChatFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - SecretsManagerReadWrite
      Events:
        ChatAPP:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ask
            Method: get
        ChatAPPPost:
          Type: Api 
          Properties:
            Path: /ask
            Method: post

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./chat_app
      DockerTag: python3.9-v1

