AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chat-comic

  Sample SAM Template for chat-comic

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 1024

Resources:
  ChatSam:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chat-comic/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          API_Key: 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
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events: 

        ApiGateway:
          Type: Api
          Properties:
            Path: /chat-comic
            Method: POST
        ApiGatewayDelete: # DELETE メソッドのトリガーを追加
          Type: Api
          Properties:
            Path: /chat-comic
            Method: DELETE